version: 2
models:
  - name: stg_currency_rates
    description: "cleaned exchange rates from raw Airflow data"
    columns:
      - name: id
        description: "primary key for the currency rates table."
        tests:
          - not_null
          - unique
      - name: rate_date
        description: "The date for which the exchange rate applies."
        tests:
          - not_null
      - name: base_currency
        description: "The base currency code"
        tests:
          - not_null
      - name: target_currency
        description: "The target currency code"
        tests:
          - not_null
      - name: exchange_rate
        description: "The exchange rate must be positive."
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "> 0"