version: 2
models:
  - name: mart_daily_rates
    description: "Daily rates pivoted for easy reporting."
    columns:
      - name: rate_date
        description: "one raw per date"
        tests:
          - not_null
          - unique
      - name: base_currency
        description: "The base currency"
        tests:
          - not_null
          
  - name: mart_daily_rates_incremental
    description: "incremental version - only processes new data since last run"
    columns:
      - name: rate_date
        tests:
          - not_null
          - unique
           
     